name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install
        run: yarn --frozen-lockfile
      - name: Build
        run: npm run docs:build
